class VariablesTheme {
    
    public static void main(String[] args) {
        System.out.println("Задание (1)-Вывод характеристик компьютера:");
        byte core = 3;
        short ram = 16;
        int dickC = 930;
        long internet = 100;
        float frequencyAmd = 3.5f;
        double assemblyOc = 19045.2604;
        char dick = 'C';
        boolean windowsPro = true;
        System.out.println("Характеристики компьютера-" + "core:" + core + ";" + "RAM:" + ram + ";" + "dickC:"
                + dickC + ";" + "internet:" + internet + ";");
        System.out.println("frequencyAMD:" + frequencyAmd + ";" + "assemblyOC:" + assemblyOc + ";" +
                "dick:" + dick + ";" + "Windows10Pro:" + windowsPro + ".");
        System.out.println("");
        System.out.println("Задание (2)-Расчет стоимости товара со скидкой:");
        int priceBook = 200;
        int pricePen = 100;
        int sum = priceBook + pricePen;
        int discount = sum / 100 * 11;
        int discountPrice = sum - discount;
        System.out.println("Общая стоимость товаров без скидки(руб.):" + sum);
        System.out.println("Сумма скидки(руб.):" + discount);
        System.out.println("Общая стоимость товаров со скидкой(руб.):" + discountPrice);
        System.out.println("");
        System.out.println("Задание (3)-Вывод слова JAVA:");
        System.out.println("   J    a   v     v  a ");
        System.out.println("   J   a a   v   v  a a");
        System.out.println("J  J  aaaaa   V V  aaaaa");
        System.out.println(" JJ  a     a   V  a     a");
        System.out.println("");
        System.out.println("Задание (4)-Вывод min и max значений целых числовых типов:");
        byte positive = 127;
        positive++;
        System.out.println(positive);
        positive--;
        System.out.println(positive);
        System.out.println("");

        short positive1 = 32767;
        positive1++;
        System.out.println(positive1);
        positive1--;
        System.out.println(positive1);
        System.out.println("");

        int positive2 = 2_147_483_647;
        positive2++;
        System.out.println(positive2);
        positive2--;
        System.out.println(positive2);
        System.out.println("");

        long positive3 = 9_223_372_036_854_775_807L;
        positive3++;
        System.out.println(positive3);
        positive3--;
        System.out.println(positive3);
        System.out.println("");
        System.out.println("Задание (5)-Перестановка значений переменных:");
        System.out.println("Вариант 1)С помощью 3 переменной:");
        int a = 2;
        int b = 5;
        int c = 0;
        System.out.println("исходные значения переменных:" + a + "/" + b);
        c += a;
        a = b;
        b = c;
        System.out.println("новые значения переменных:" + a + "/" + b);
        System.out.println("");
        System.out.println("Вариант 2)С помощью арифметических операций:");
        int num1 = 2;
        int num2 = 5;
        System.out.println("исходные значения переменных:" + num1 + "/" + num2);
        num1 += num2;
        num2 -= num1;
        num1 -= num2;
        System.out.println("новые значения переменных:" + num1 + "/" + num2);
        System.out.println("");
        System.out.println("Вариант 3) помощью побитовой операции ^:");
        int num3 = 2;
        int num4 = 5;
        System.out.println("исходные значения переменных:" + num3 + "/" + num4);
        num3 ^= num4;
        num4 ^= num3;
        num3 ^= num4;
        System.out.println("новые значения переменных:" + num3 + "/" + num4);
        System.out.println("");
        System.out.println("Задание (6)-Вывод символов и их кодов:");
        char number = '#';
        int cod = 35;
        System.out.println(  cod + " = " + number);
        char ampersand = '&';
        int cod2 = 38;
        System.out.println( cod2 + " = " + ampersand);
        char atsign = '@';
        int cod3 = 64;
        System.out.println(cod3 + " = " + atsign);
        char circumflex = '^';
        int cod4 = 94;
        System.out.println( cod4 + " = " + circumflex);
        char underscorenum = '_';
        int cod5 = 95;
        System.out.println( cod5 + " = " + underscorenum);
        System.out.println("");
        System.out.println("Задание (7)-Вывод в консоль ASCII-арт Дюка:");
        char slash = '/';
        char backslash = '\\';
        char underscore = '_';
        char leftparenthesis = '(';
        char rightparenthesis = ')';
        System.out.println(" " + slash + "" + backslash);
        System.out.println(" " + slash + " " + underscore);
        System.out.println(" " + slash + underscore + leftparenthesis + " " + rightparenthesis + "" + backslash);
        System.out.println(" " + slash + " " + backslash);
        System.out.println(" " + slash + underscore + underscore + underscore + underscore + slash +
                backslash + backslash + backslash + underscore);
        System.out.println("");
        System.out.println("Задание (8)-Вывод количества сотен, десятков и единиц числа");
        int num = 123;
        int aA = 1;
        int bB = 2;
        int cC = 3;
        int ten = 10;
        int hundred = 100;
        int numberOfTens = num / ten;
        int numberOfHundred = num / hundred;
        int numberOfUnits = num % ten + num % hundred;
        int sum1 = numberOfTens + numberOfHundred + numberOfUnits;
        int sum2 = aA + bB + cC;
        int result1 = aA - bB - cC;
        System.out.println("Число 123 содержит:");
        System.out.println("десятков:" + numberOfTens);
        System.out.println("Сотен:" + numberOfHundred);
        System.out.println("единиц:" + numberOfUnits);
        System.out.println("Сумма его значений:" + sum1);
        System.out.println("Сумма его цифр:" + sum2);
        System.out.println("Произведение:" + result1);
        System.out.println("");
        System.out.println("Задание (9)-Вывод времени");
        int seconds = 86399;
        int minutes = seconds / 60;
        int sec2 = seconds % 60;
        int watch = minutes / 60;
        int min2 = minutes % 60;
        System.out.println(watch + ":" + min2 + ":" + sec2);

    }
}
